"""Build SEG-Y files on purpose, including wrong ones.

There is no other way to test a reader honestly. Real deliveries arrive in the
shapes their vendors happened to write; they cannot be asked for a file with two
extended textual headers, a variable trace length and a declared revision that
contradicts its own structure. So the library builds them.

Two design rules make this more than a test helper:

  * **The writer uses the reader's field tables.** A fixture is written through
    the same `FieldDef` objects the parser reads through, so the two cannot
    drift. When the rev 2.1 writer arrives it grows out of this module rather
    than beside it.
  * **Every lie is a named knob.** `declared_revision`, `declared_trace_count`
    and their siblings let a fixture declare one thing and contain another,
    which is the only way to test that the reader notices. Defaults are always
    truthful: a builder left alone produces a correct file.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any, Sequence

from . import binary_header as bh
from . import trace_header as th
from .textual import CARD_WIDTH, CARDS_PER_HEADER, TEXTUAL_HEADER_SIZE
from .types import SAMPLE_BYTES, SAMPLE_DTYPE, Endian, encode_scalar

END_TEXT_STANZA = "((SEG: EndText))"


@dataclass
class Trace:
    """One trace: header values by field name, plus samples."""

    headers: dict[str, Any] = field(default_factory=dict)
    samples: Sequence[float] | None = None
    #: Values for the additional rev 2 trace headers, one dict per extension.
    #: Each may carry `trace_header_name`; anything else is written by byte.
    extensions: list[dict[str, Any]] = field(default_factory=list)


def default_textual(lines: Sequence[str] | None = None) -> str:
    """40 cards of 80 characters, numbered the way processors number them."""
    body = list(lines or [
        "CLIENT: OPENSEGY SYNTHETIC",
        "LINE:   TEST",
        "THIS FILE WAS GENERATED BY OPENSEGY FOR TESTING.",
        "COORDINATE UNITS: METERS",
        "CDP X BYTES 181-184  CDP Y BYTES 185-188",
        "INLINE BYTES 189-192  CROSSLINE BYTES 193-196",
    ])
    cards = []
    for i in range(CARDS_PER_HEADER):
        text = body[i] if i < len(body) else ""
        cards.append(f"C{i + 1:2d} {text}"[:CARD_WIDTH].ljust(CARD_WIDTH))
    return "".join(cards)


def _encode_textual(text: str, encoding: str) -> bytes:
    padded = text.ljust(TEXTUAL_HEADER_SIZE)[:TEXTUAL_HEADER_SIZE]
    return padded.encode(encoding, errors="replace")


def _cardify(text: str) -> str:
    """Lay free text out as 80-column cards, which is what a record is."""
    cards = []
    for line in text.split("\n"):
        while len(line) > CARD_WIDTH:
            cards.append(line[:CARD_WIDTH])
            line = line[CARD_WIDTH:]
        cards.append(line.ljust(CARD_WIDTH))
    return "".join(cards)


class SegyBuilder:
    """Assemble a SEG-Y file in memory.

    Every argument that starts with `declared_` writes a value into the header
    without changing what is actually produced, which is how a deliberately
    inconsistent fixture is made.
    """

    def __init__(
        self,
        *,
        revision: tuple[int, int] = (1, 0),
        endian: Endian = Endian.BIG,
        sample_format: int = 5,
        samples_per_trace: int = 51,
        sample_interval_us: int = 4000,
        textual: str | None = None,
        textual_encoding: str = "cp037",
        extended_textual: Sequence[str] = (),
        extra_trace_headers: int = 0,
        fixed_length: bool = True,
        survey_type: int | None = None,
        data_trailer: Sequence[str] = (),
        measurement_system: int = 1,
        declared_revision: tuple[int, int] | None = None,
        declared_extended_count: int | None = None,
        declared_trace_count: int | None = None,
        declared_first_trace_offset: int | None = None,
        declared_samples_per_trace: int | None = None,
        write_byte_order_constant: bool | None = None,
    ) -> None:
        if sample_format not in SAMPLE_BYTES:
            raise ValueError(f"unknown sample format code {sample_format}")
        self.revision = revision
        self.endian = endian
        self.sample_format = sample_format
        self.samples_per_trace = samples_per_trace
        self.sample_interval_us = sample_interval_us
        self.textual = textual if textual is not None else default_textual()
        self.textual_encoding = textual_encoding
        self.extended_textual = list(extended_textual)
        self.extra_trace_headers = extra_trace_headers
        self.fixed_length = fixed_length
        self.survey_type = survey_type
        self.data_trailer = list(data_trailer)
        self.measurement_system = measurement_system
        self.declared_revision = declared_revision or revision
        self.declared_extended_count = declared_extended_count
        self.declared_trace_count = declared_trace_count
        self.declared_first_trace_offset = declared_first_trace_offset
        self.declared_samples_per_trace = declared_samples_per_trace
        self.write_byte_order_constant = (
            revision >= (2, 0) if write_byte_order_constant is None
            else write_byte_order_constant)
        self.traces: list[Trace] = []

    # ── building ─────────────────────────────────────────────────────────────

    def add_trace(self, headers: dict[str, Any] | None = None,
                  samples: Sequence[float] | None = None,
                  extensions: list[dict[str, Any]] | None = None) -> "SegyBuilder":
        self.traces.append(Trace(headers=dict(headers or {}),
                                 samples=samples,
                                 extensions=list(extensions or [])))
        return self

    def add_grid(self, *, inlines: Sequence[int], crosslines: Sequence[int],
                 origin: tuple[float, float] = (500_000.0, 7_500_000.0),
                 bin_size: tuple[float, float] = (25.0, 25.0),
                 scalar: int = -100) -> "SegyBuilder":
        """A rectangular 3D survey, line-major, with coordinates on a lattice.

        Coordinates are written as scaled integers the way real files do it, so
        a reader that forgets to apply the scalar gets an answer that is wrong
        by exactly the factor the fixture is testing for.
        """
        factor = float(-scalar) if scalar < 0 else 1.0
        for il_i, il in enumerate(inlines):
            for xl_i, xl in enumerate(crosslines):
                x = origin[0] + xl_i * bin_size[0]
                y = origin[1] + il_i * bin_size[1]
                self.add_trace({
                    "trace_sequence_file": len(self.traces) + 1,
                    "ensemble": il_i * len(crosslines) + xl_i + 1,
                    "inline": il,
                    "crossline": xl,
                    "coordinate_scalar": scalar,
                    "cdp_x": int(round(x * factor)),
                    "cdp_y": int(round(y * factor)),
                    "source_x": int(round(x * factor)),
                    "source_y": int(round(y * factor)),
                    "samples_per_trace": self.samples_per_trace,
                    "sample_interval": self.sample_interval_us,
                    "trace_id": 1,
                })
        return self

    # ── emitting ─────────────────────────────────────────────────────────────

    def build(self) -> bytes:
        parts: list[bytes] = [_encode_textual(self.textual, self.textual_encoding)]

        ext_records = self._extended_records()
        first_trace_offset = (bh.BASE_DATA_START
                              + len(ext_records) * TEXTUAL_HEADER_SIZE)

        parts.append(self._binary_header(len(ext_records), first_trace_offset))
        parts.extend(ext_records)
        for index, trace in enumerate(self.traces):
            parts.append(self._trace(index, trace))
        for record in self.data_trailer:
            parts.append(_encode_textual(_cardify(record), self.textual_encoding))
        return b"".join(parts)

    def write(self, path) -> str:
        data = self.build()
        with open(path, "wb") as fh:
            fh.write(data)
        return str(path)

    # ── pieces ───────────────────────────────────────────────────────────────

    def _extended_records(self) -> list[bytes]:
        texts = list(self.extended_textual)
        if self.declared_extended_count == -1 and not any(
                END_TEXT_STANZA in t for t in texts):
            texts.append(END_TEXT_STANZA)
        return [_encode_textual(_cardify(t), self.textual_encoding) for t in texts]

    def _binary_header(self, n_extended: int, first_trace_offset: int) -> bytes:
        block = bytearray(bh.BINARY_HEADER_SIZE)
        # The structures written are those of `revision`; only the two bytes at
        # 3501-3502 follow `declared_revision`. Keeping them apart is the whole
        # point of the knob: a fixture that declares rev 1 while carrying rev 2
        # fields is the file this library exists to notice.
        major, minor = self.revision
        declared_major, declared_minor = self.declared_revision
        values: dict[str, Any] = {
            "job_id": 1,
            "line_number": 1,
            "reel_number": 1,
            "traces_per_ensemble": 1,
            "sample_interval": self.sample_interval_us,
            "sample_interval_orig": self.sample_interval_us,
            "samples_per_trace": (self.declared_samples_per_trace
                                  if self.declared_samples_per_trace is not None
                                  else self.samples_per_trace),
            "samples_per_trace_orig": self.samples_per_trace,
            "sample_format": self.sample_format,
            "measurement_system": self.measurement_system,
            "trace_sorting": 4,
            "revision_major": declared_major,
            "revision_minor": declared_minor,
        }
        if (major, minor) >= (1, 0):
            values["fixed_length_trace_flag"] = 1 if self.fixed_length else 0
            values["extended_textual_headers"] = (
                self.declared_extended_count
                if self.declared_extended_count is not None else n_extended)
        if (major, minor) >= (2, 0):
            if self.write_byte_order_constant:
                values["byte_order_constant"] = 0x01020304
            values["ext_samples_per_trace"] = self.samples_per_trace
            values["ext_sample_interval"] = float(self.sample_interval_us)
            values["max_extra_trace_headers"] = self.extra_trace_headers
            values["trace_count"] = (
                self.declared_trace_count
                if self.declared_trace_count is not None else len(self.traces))
            values["first_trace_offset"] = (
                self.declared_first_trace_offset
                if self.declared_first_trace_offset is not None
                else first_trace_offset)
            values["time_basis"] = 4
            values["data_trailer_stanzas"] = len(self.data_trailer)
        if (major, minor) >= (2, 1) and self.survey_type is not None:
            values["survey_type"] = self.survey_type

        table = {f.name: f for f in bh.fields_for(major, minor)}
        for name, value in values.items():
            fd = table.get(name)
            if fd is None or value is None:
                continue
            raw = encode_scalar(value, fd.dtype, self.endian)
            block[fd.start - 1:fd.start - 1 + fd.width] = raw

        # The byte-order constant is written big-endian by definition: it is the
        # thing that tells a reader which way round everything else is.
        if self.write_byte_order_constant and (major, minor) >= (2, 0):
            block[96:100] = (0x01020304).to_bytes(4, "big") \
                if self.endian is Endian.BIG else (0x01020304).to_bytes(4, "little")
        return bytes(block)

    def _trace(self, index: int, trace: Trace) -> bytes:
        n = (len(trace.samples) if trace.samples is not None
             else self.samples_per_trace)
        header = bytearray(th.TRACE_HEADER_SIZE)
        # The full table, so a rev 0 fixture can carry the inline that real
        # rev 0 deliveries carry.
        table = {f.name: f for f in th.fields_for()}
        base: dict[str, Any] = {
            "trace_sequence_line": index + 1,
            "trace_sequence_file": index + 1,
            "samples_per_trace": n,
            "sample_interval": self.sample_interval_us,
            "trace_id": 1,
        }
        base.update(trace.headers)
        for name, value in base.items():
            fd = table.get(name)
            if fd is None or value is None:
                continue
            header[fd.start - 1:fd.start - 1 + fd.width] = encode_scalar(
                value, fd.dtype, self.endian)

        blocks = [bytes(header)]
        for i in range(self.extra_trace_headers):
            ext = bytearray(th.TRACE_HEADER_SIZE)
            spec = trace.extensions[i] if i < len(trace.extensions) else {}
            name = spec.get("trace_header_name", f"EXT{i + 1:05d}")
            ext[232:240] = encode_scalar(name, "char8", self.endian)
            for key, value in spec.items():
                if key == "trace_header_name":
                    continue
                # Extensions are vendor space: address them by byte directly.
                start, dtype = key if isinstance(key, tuple) else (None, None)
                if start is None:
                    continue
                raw = encode_scalar(value, dtype, self.endian)
                ext[start - 1:start - 1 + len(raw)] = raw
            blocks.append(bytes(ext))

        samples = trace.samples
        if samples is None:
            samples = _ricker(n, index)
        dtype = SAMPLE_DTYPE[self.sample_format]
        body = b"".join(encode_scalar(v, dtype, self.endian) for v in samples)
        return b"".join(blocks) + body


def _ricker(n: int, seed: int = 0) -> list[float]:
    """A deterministic wavelet, so a fixture's bytes never change between runs."""
    centre = n / 2.0 + (seed % 5)
    sigma = max(2.0, n / 12.0)
    out = []
    for i in range(n):
        t = (i - centre) / sigma
        out.append((1.0 - 2.0 * t * t) * math.exp(-t * t))
    return out
